[project]
name = "jupyter-summarytools"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.16.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=1.4",
    "scipy>=1.18.0",
]
[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = [
    "setuptools>=65.5.0",
    "wheel"
]

[dependency-groups]
dev = [
    "ruff>=0.16.2",
]
